import { StoreProvider } from "@/store/store";
import "../styles/globals.css";
export const metadata = {
  title: "Weather User",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className="h-[100vh] bg-gray-500">{children}</body>
      </html>
    </StoreProvider>
  );
}
